### ISSUE TITLE
Pass in `context` when rendering stateless components

### ISSUE THREAD

**Issue by choonkending** [ngerritsen/react-stateless-wrapper#3]
Not sure whether this is intentional, but I reckon it would be useful to pass in `context` when wrapping the stateless component. [Docs here](https://facebook.github.io/react/docs/context.html#referencing-context-in-stateless-functional-components). 

Recently ran into this when writing a test for a stateless component that needed to accept `context` in the argument.

I modified this locally and it worked really well.

``` javascript

function wrap(statelessComponent) {
  return React.createClass({
    displayName: statelessComponent.name,
    render: function() {
      return statelessComponent(this.props, this.context);
    }
  });
}

```

Let me know what you think (or whether you think stubbing the context should be handled by another wrapper). 

Good work with this wrapper btw!

**Comment by ngerritsen** [comment]
That looks pretty much like what you'd expect! If you could make a pull
request for this that would be nice. If we need another way to pass in
context for unit tests that can always be added later.
Op ma 15 feb. 2016 om 07:32 schreef Ken Ding notifications@github.com

**Comment by choonkending** [comment]
^ PR ready for you. Let me know what you think :smile:
